# Generated by Django 3.0.5 on 2021-04-23 08:09

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210423_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='imagesofuser/', verbose_name='ImageofUser'),
        ),
        migrations.DeleteModel(
            name='ImageofUser',
        ),
    ]
