# Generated by Django 3.0.5 on 2021-04-21 08:57

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_imageofevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.ImageofEvent'),
        ),
        migrations.AlterField(
            model_name='imageofevent',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='ImageofEvent'),
        ),
    ]
