# Generated by Django 3.0.5 on 2021-04-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210421_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageofevent',
            name='name',
        ),
    ]
