# Generated by Django 3.0.5 on 2021-04-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210422_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageofEvent',
        ),
    ]
